### ISSUE TITLE
dont print modules when all modules are disabled

### ISSUE THREAD

**Issue by craftamap** [livelyapps/pluploader#11]
When all modules are disabled after uploading, it is more like a spam instead
of information when a list of all disabled modules is printed.

Sven therefore suggested to modify the error message to read: 

"Your plugin was installed successfully but all modules are disabled.
This is often caused by problems such as importing services that are
not properly defined in your atlassian-plugin.xml."

**Comment by sschatter** [comment]
Would add: Check the logs of your Atlassian host to find out more.
