### ISSUE TITLE
No support for https?

### ISSUE THREAD

**Issue by EugenMayer** [livelyapps/pluploader#31]
using 

```
host: myhost.com
port: 443
user: ..
password: ...
```
i always get  `An error occured - check your credentials` - is tls not supported?

**Comment by craftamap** [comment]
Hey @EugenMayer ,

TLS is supported, however, you need to use the `scheme` option set to `https`.

Does this work for you?

**Comment by EugenMayer** [comment]
well i did not find the options one can use.. just after reading the cod https://github.com/livelyapps/pluploader/blob/master/scripts/pluploader.py#L76

thanks that works. Maybe the readme could need some love :) Thanks it works!

**Comment by craftamap** [comment]
You're right, the readme needs some more love. :)

Thanks for using the pluploader!
