### ISSUE TITLE
Cannot install cloud descriptor

### ISSUE THREAD

**Issue by EugenMayer** [livelyapps/pluploader#64]
I cannot install a cloud plugin descriptor. Neither using user/password or user/api toke (from https://id.atlassian.com/manage-profile/security/api-tokens). Always getting that the UPM token cannot be retrieved.

```
pluploader install --cloud -u https://.../addon-descriptor.json 
```

base_url /username/password set via .pluprc
base_url looks like `https://some.atlassian.net`

tried it with the cli and docker version (0.7.0)

any hints?

**Comment by craftamap** [comment]
Hey @EugenMayer ,

Thanks for reporting this! I will try it out later today. Could you tell me if you are using a jira addon or a confluence addon? 

Cheers, Fabian!

**Comment by EugenMayer** [comment]
confluence addon was it in my case

**Comment by EugenMayer** [comment]
Adding `/wiki` and using an API token fixes it. In my case, using the password does not work. Not sure if that already is blacklisted.

Maybe we should add this to the docs, that the cloud instances must be suffixed with /wiki?

Or even validate when running --cloud?

Anyway, solved for me - probably some doc updates would be perfect. Thanks!

**Comment by craftamap** [comment]
In this case, I will continue the discussion in #67 and close the ticket. Thanks for the help!
